name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          enable_kvm: true
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - uses: cachix/cachix-action@v16
        with:
          name: dshpot
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: check
        run: nix flake check
      - name: build container
        if: github.ref == 'refs/heads/main'
        run: nix build .#container
      - name: push container to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          docker load < $(readlink -f result)
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag dshpot:latest ghcr.io/${IMAGE_NAME}:latest
          docker tag dshpot:latest ghcr.io/${IMAGE_NAME}:${{ github.sha }}
          docker push ghcr.io/${IMAGE_NAME}:latest
          docker push ghcr.io/${IMAGE_NAME}:${{ github.sha }}
